- name: Terraform Apply (ALB only)
  run: |
    cd modules/${{ github.event.inputs.module }}
    terraform apply -auto-approve -input=false \
      -target="aws_lb.app_alb" \
      -target="aws_security_group.alb_sg" \
      -target="aws_lb_target_group.app_tg" \
      -target="aws_lb_listener.http"
